/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.verdesmart;

/**
 *
 * @author Brith
 */
public class delete extends javax.swing.JFrame {


   
    private grounds home_page; // Reference to the main dashboard frame layout
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(delete.class.getName());
    private int idGardenEliminar;  // The target identifier key of the garden to be deleted

   /**
     * Creates new form delete context mapped to a primary screen and a specific record ID.
     */
    public delete(grounds page_home, int idGarden) {
        this.home_page = page_home;
        this.idGardenEliminar = idGarden;
        initComponents();
        
        btncancel.putClientProperty("FlatLaf.style", ""
                + "background: #1B4D2F;"
                + "foreground: #FFFFFF;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "arc: 999;");
  
        btndelete.putClientProperty("FlatLaf.style", ""
                + "background: #1B4D2F;"
                + "foreground: #FFFFFF;"
                + "borderWidth: 0;"
                + "focusWidth: 0;"
                + "arc: 999;");
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(199, 221, 181));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 77, 47));
        jLabel1.setText("Eliminar Jardín");

        btncancel.setText("Canclar");
        btncancel.addActionListener(this::btncancelActionPerformed);

        btndelete.setText("Eliminar");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action handler for the cancel button.
     * Redirects the user back to the primary dashboard view without dropping database data.
     */
    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
    // CAMBIADO: Regresar a grounds al cancelar
        if (this.home_page != null) {
            this.home_page.setVisible(true); 
        }
        this.dispose();
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * Action handler for the delete button.
     * Prompts for final validation confirmation before dropping the specified record context 
     * using safe SQL transaction rollbacks.
     */
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

            // Display confirmation alert before performing permanent cascading data removal
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que deseas eliminar este jardín? Esta acción borrará de forma permanente todas las plantas, monitoreos e irrigaciones asociadas.", 
            "Confirmar Eliminación", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (respuesta != javax.swing.JOptionPane.YES_OPTION) {
            return; 
        }

        String sqlDeleteGarden = "DELETE FROM garden WHERE id_Garden = ?";
        java.sql.Connection con = null;

        try {
            con = DatabaseConnection.getInstance().getConnection();
            con.setAutoCommit(false); 

            try (java.sql.PreparedStatement psGarden = con.prepareStatement(sqlDeleteGarden)) {
                psGarden.setInt(1, idGardenEliminar);
                int filasJardin = psGarden.executeUpdate();

                if (filasJardin > 0) {
                    con.commit(); 
                    javax.swing.JOptionPane.showMessageDialog(this, "El jardín y sus datos asociados se eliminaron correctamente.");
                    
                    // MODIFICADO: Forzamos un reinicio limpio de la pantalla grounds para que se limpie por completo
                    grounds nuevaPantalla = new grounds();
                    nuevaPantalla.setVisible(true);
                    
                    // Cerramos la pantalla vieja que estaba en segundo plano
                    if (this.home_page != null) {
                        this.home_page.dispose();
                    }
                    this.dispose();
                } else {
                    con.rollback(); 
                    javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el jardín especificado en la base de datos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (java.sql.SQLException ex) {
            if (con != null) {
                try { con.rollback(); } catch (java.sql.SQLException e) { logger.log(java.util.logging.Level.SEVERE, null, e); }
            }
            logger.log(java.util.logging.Level.SEVERE, "Error en la transacción de eliminación", ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar: " + ex.getMessage(), "Error SQL", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            if (con != null) {
                try { con.setAutoCommit(true); } catch (java.sql.SQLException e) { logger.log(java.util.logging.Level.SEVERE, null, e); }
            }
        }
    
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
