/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.verdesmart;
import java.sql.Connection;
/**
 *
 * @author Brith
 */
public class forrgotten_password extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(forrgotten_password.class.getName());

    /**
     * Creates new form forrgotten_password
     */
    public forrgotten_password() {
        initComponents();
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jButton2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        jButton2.setText("jButton2");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton2)))
                .addContainerGap(648, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addGap(83, 83, 83)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                                       
    
    String email = jTextField1.getText().trim(); 
    String user = jTextField2.getText().trim(); 
    
    // Validar que los campos no estén vacíos
    if (email.isEmpty() || user.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos.");
        return;
    }
    String sql = "SELECT * FROM user_user WHERE e_mail = ? AND Name_user = ?  ";
    
    
    
    try {
        Connection con = ConexionBaseDatos.getInstancia().getConexion();
        
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, email);
        ps.setString(2, user);
        
        java.sql.ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            String nameuser = rs.getString("Name_user");
            javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido de nuevo, " + nameuser + "!");
            jTextField3.setEnabled(true);
            jTextField4.setEnabled(true);
            jButton2.setEnabled(true);
            
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jButton1.setEnabled(false);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuario o correo son incorrectos", "Error de Autenticación", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        ps.close();
        rs.close();
        
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos: " + e.getMessage());
    }
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                              
    // 1. Obtener las contraseñas que el usuario escribió en las cajas 3 y 4
    String pass1 = jTextField3.getText().trim();
    String pass2 = jTextField4.getText().trim();
    
    // Recuperamos el correo de la caja 1 (que ya fue validado en el Botón 1)
    // Lo usamos como filtro para saber exactamente a qué usuario modificarle la contraseña
    String email = jTextField1.getText().trim(); 

    // 2. Validar que no hayan dejado los campos vacíos
    if (pass1.isEmpty() || pass2.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, escribe la nueva contraseña en ambos campos.");
        return;
    }

    // 3. Validar que ambas contraseñas coincidan exactamente
    if (!pass1.equals(pass2)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden. Inténtalo de nuevo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Sentencia SQL para hacer la actualización real en tu tabla 'user_user'
    String sqlUpdate = "UPDATE user_user SET Password_user = ? WHERE e_mail = ?";

    // 5. Conectarse y ejecutar la actualización en la Base de Datos
    try (Connection con = ConexionBaseDatos.getInstancia().getConexion();
         java.sql.PreparedStatement ps = con.prepareStatement(sqlUpdate)) {
        
        // Pasamos los datos al query (? , ?)
        ps.setString(1, pass1); // Nueva contraseña
        ps.setString(2, email); // Filtro de correo electrónico

        // executeUpdate() devuelve cuántas filas se modificaron en MySQL
        int filasAfectadas = ps.executeUpdate();

        if (filasAfectadas > 0) {
            // ¡Éxito! Se guardó en la base de datos
            javax.swing.JOptionPane.showMessageDialog(this, "¡Contraseña actualizada con éxito en la base de datos!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Cierra la ventana actual de recuperación automáticamente
            this.dispose(); 
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "No se encontró el correo del usuario para actualizar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (java.sql.SQLException e) {
        // En caso de que falle la comunicación con MySQL
        logger.log(java.util.logging.Level.SEVERE, "Error al actualizar contraseña", e);
        javax.swing.JOptionPane.showMessageDialog(this, "Error crítico de Base de Datos:\n" + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
